language: python

python:
- "3.4"
- "3.5"
- "3.6"

matrix:
  include:
  - python: 3.7
    dist: xenial

install:
- sudo apt-get update -qq
- sudo apt-get install -qq qtbase5-dev qt5-default g++ make cmake
- pip install --upgrade pip
- pip install tox

script:
- tox -e py$(echo $TRAVIS_PYTHON_VERSION | tr -d .)
