language: python

python:
- "3.6"

matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: bionic

install:
- sudo apt-get update -qq
- sudo apt-get install -qq qtbase5-dev qt5-default g++ make cmake ninja-build
- pip install --upgrade pip
- pip install tox

script:
- tox -e py$(echo $TRAVIS_PYTHON_VERSION | tr -d .)
